<?php

$record = $block->getEditRecord();
?>
<form class="" action="<?php echo $block->getBaseUrl().'crud/index/save'; ?>" id="crud-form" method="post" enctype='multipart/form-data'  data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span>Test Form <a href="<?php echo $block->getBaseUrl().'crud/index/index'; ?>">(Visit List Page)</a></span></legend><br>
        <div class="field note no-label">Write here anything you want.</div>
        <div class="field name">
            <label class="label" for="name"><span>Post Name</span></label>
            <div class="control">
                <input name="name" id="name" title="Name" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field url_key">
            <label class="label" for="url_key"><span>Post URL Key</span></label>
            <div class="control">
                <input name="url_key" id="url_key" title="Post URL Key" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field post_content">
            <label class="label" for="post_content"><span>Post Content</span></label>
            <div class="control">
                <textarea name="post_content" id="post_content" title="Post Content" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
         <div class="field tags">
            <label class="label" for="tags"><span>Post Tags</span></label>
            <div class="control">
                <input name="tags" id="tags" title="Post Tags" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field featured_image">
            <label class="label" for="featured_image"><span>Post Featured Image</span></label>
            <div class="control">
                <input name="featured_image" id="featured_image" title="Post Featured Image" value="" class="input-text" type="file">
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>
