<form class="" action="<?php echo $block->getBaseUrl().'book/index/save'; ?>" id="book-form" method="post" enctype='multipart/form-data'  data-mage-init='{"validation": {}}'>
    <fieldset class="fieldset">
        <legend class="legend"><span>Test Form For Book Module <a href="<?php echo $block->getBaseUrl().'book/index/list'; ?>">(Visit List Page)</a></span></legend><br>
        <div class="field note no-label">Write here anything you want.</div>
        <div class="field book_type">
            <label class="label" for="title"><span>Book Type</span></label>
            <div class="control">
                <select id="book_type" name="book_type" title="<?= $block->escapeHtmlAttr(__('Book')) ?>" class="select" data-validate="{required:true}">
                    <option value="">-- Please Select --</option>
                    <option data-title="Horror" value="Horror">Horror</option>
                    <option data-title="Romance" value="Romance">Romance</option>
                    <option data-title="Thriller" value="Thriller">Thriller</option>
                    <option data-title="Biography" value="Biography">Biography</option>
                    <option data-title="Comedy" value="Comedy">Comedy</option>
                </select>
            </div>
        </div>
        <div class="field name">
            <label class="label" for="author"><span>Name</span></label>
            <div class="control">
                <input name="name" id="name" title="Name" value="" class="input-text" type="text" data-validate="{required:true}">
            </div>
        </div>
        <div class="field content">
            <label class="label" for="content"><span>Content</span></label>
            <div class="control">
                <textarea name="content" id="content" title="Content" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div>
        <div class="field author">
            <label class="label" for="author"><span>Author</span></label>
            <div class="control">
                <select name="author[]" id="author" title="Author" class="multiple" type="text" data-validate="{required:true}" multiple>
                    <option data-title="Chetan Bhagat" value="Chetan Bhagat">Chetan Bhagat</option>
                    <option data-title="Vikram Seth" value="Vikram Seth">Vikram Seth</option>
                    <option data-title="Arundhati Roy" value="Arundhati Roy">Arundhati Roy</option>
                    <option data-title="Khushwant Singh" value="Khushwant Singh">Khushwant Singh</option>
                </select>
            </div>
        </div>
        <div class="field color">
            <label class="label" for="image"><span>Color</span></label>
            <div class="control">
                <input name="color" id="color" title="Color" value="" class="input-text" type="color">
            </div>
        </div>
        <div class="field language">
            <label class="label" for="image"><span>Language</span></label>
            <div class="control">
                <div class="input-box">
                    <input type="checkbox" name="language[]" value="Hindi" class="checkbox"> Hindi
                </div>
                <div class="input-box">
                    <input type="checkbox" name="language[]" value="English" class="checkbox"> English
                </div>
                <div class="input-box">
                    <input type="checkbox" name="language[]" value="Marathi" class="checkbox"> Marathi
                </div>
                <div class="input-box">
                    <input type="checkbox" name="language[]" value="Gujarati" class="checkbox"> Gujarati
                </div>
            </div>
        </div>
        <div class="field rating">
            <label class="label" for="image"><span>Rating</span></label>
            <div class="control">
                <div class="input-box">
                    <input type="radio" name="rating" value="1" class="radio"> 1 Star
                </div>
                <div class="input-box">
                    <input type="radio" name="rating" value="2" class="radio"> 2 Star
                </div>
                <div class="input-box">
                    <input type="radio" name="rating" value="3" class="radio"> 3 Star
                </div>
                <div class="input-box">
                    <input type="radio" name="rating" value="4" class="radio"> 4 Star
                </div>
                <div class="input-box">
                    <input type="radio" name="rating" value="5" class="radio"> 5 Star
                </div>
            </div>
        </div>
        <div class="field rating">
            <label class="label" for="image"><span>Visible</span></label>
            <div class="control">
                <div class="input-box">
                    <input type="radio" name="status" value="0" class="radio"> Disable
                </div>
                <div class="input-box">
                    <input type="radio" name="status" value="1" class="radio"> Enable
                </div>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" title="Submit" class="action submit primary">
                <span>Submit</span>
            </button>
        </div>
    </div>
</form>
