<?php
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);
$father_name = $config->getConfigValue('customer/general/father_name');
$mother_name = $config->getConfigValue('customer/general/mother_name');
?>
<fieldset class="fieldset create account">
       <?php if($father_name || $mother_name): ?>
		<legend class="legend"><span><?php /* @escapeNotVerified */
	            echo __('Additional Information') ?></span></legend>
	<p>
        <?php if($father_name): ?>
		<div class="field father_name">
	    	<label for="Father Name" class="label"><span><?php /* @escapeNotVerified */
	            echo __('Your Father Name') ?></span></label>
	    	<div class="control">
	        	<input type="text" class="input-text" name="father_name" id="father_name" value="" />
	    	</div>
		</div>
        <?php endif; ?>
        <?php if($mother_name): ?>
		<div class="field mother_name">
	    	<label for="Mother Name" class="label"><span><?php /* @escapeNotVerified */
	            echo __('Your Mother Name') ?></span></label>
	    	<div class="control">
	        	<input type="text" class="input-text" name="mother_name" id="mother_name" value="" />
	    	</div>
		</div>
        <?php endif; ?>
	</p>
<?php endif; ?>
</fieldset>
