<?php
    $blockGrid = $block->getBlockGrid();
    $gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="product_ids" data-form-part="custom_form" id="product_ids" value=""  />
<script type="text/x-magento-init">
    {
        "*": {
            "AffectedProducts_TaskModule/js/assign-products": {
                "selectedProducts":  <?= /* @escapeNotVerified */ $block->getProductsJson() ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */ '"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>

